### ISSUE TITLE
"'unknown' is not a valid HVACMode" Error Message in Logs 

### ISSUE THREAD

**Issue by Jonah1970** [piitaya/home-assistant-qubino-wire-pilot#5]
I have noticed the following errors appearing in my logs recently but am unsure when they started.  Things seem to be working OK but I thought I would report it in case it is a problem with the Integration.  It looks like it might be an issue on startup, HA version is 2022.5.2.

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:220
Integration: Climate (documentation, issues)
First occurred: 17:32:08 (5 occurrences)
Last logged: 17:32:08
```
Error adding entities for domain climate with platform qubino_wire_pilot
Error while setting up qubino_wire_pilot platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 220, in state
    return HVACMode(self.hvac_mode).value
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'unknown' is not a valid HVACMode
```
My config is pretty standard as below:
```
- platform: qubino_wire_pilot
  name: Zone1 Thermostat
  heater: light.qubino_pw01_level
  sensor: sensor.bed3_temperature
  additional_modes: true
  
- platform: qubino_wire_pilot
  name: Zone2 Thermostat
  heater: light.qubino_pw02_level
  sensor: sensor.lounge_temperature
  additional_modes: true
  
- platform: qubino_wire_pilot
  name: Study Thermostat
  heater: light.qubino_pw03_level
  sensor: sensor.study_temperature
  additional_modes: true
 
- platform: qubino_wire_pilot
  name: Bed1 Thermostat
  heater: light.qubino_pw04_level
  sensor: sensor.bed1_temperature
  additional_modes: true
```

**Comment by plouf34** [comment]
Any news? I’ve the same error

**Comment by dx44** [comment]
Le problème est normalement depuis la version 2022.05 de HA. Un breaking change qui impacte cette intégration : https://github.com/home-assistant/core/pull/69077

**Comment by c7274864** [comment]
Hello

Would it be possible to have a fix?
because I have the same error, grrr....

THANKS

**Comment by trollix** [comment]
Hello, the same for me:
<img width="860" alt="screenshot_1470" src="https://github.com/piitaya/home-assistant-qubino-wire-pilot/assets/3890545/ab74b957-f2cc-4233-b0f1-c021c703a3b4">
<img width="533" alt="screenshot_1469" src="https://github.com/piitaya/home-assistant-qubino-wire-pilot/assets/3890545/9456c275-56d5-4c72-8086-842c7a8ade02">

**Comment by piitaya** [comment]
Fixed with https://github.com/piitaya/home-assistant-qubino-wire-pilot/pull/6
